source 'https://rubygems.org'

gem 'rails', '3.2.15'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

# server
gem 'thin'
gem 'whenever', :require => false
gem 'delayed_job_active_record'
gem 'newrelic_rpm'
gem 'airbrake'

# data
gem 'pg'
gem 'activerecord-postgres-hstore'
gem 'pg_search'
# Use foreginer and immigrant to handle auto-indexing of foreign_keys
# postgresql doesn't generate fk index
gem 'foreigner'
gem 'immigrant'
gem 'paper_trail', '>= 3.0.0.beta1'
gem 'simple_enum'
gem 'has_scope'
gem 'attribute_normalizer'
gem 'acts_as_list'
gem 'role_model'
gem 'state_machine'
gem 'carrierwave'
gem 'aws'
gem 'oj'
gem 'rabl'

# user
gem 'cancan'
gem 'devise', '~> 3.0.0'
gem 'omniauth'
gem 'omniauth-google-oauth2'
gem 'omniauth-facebook'

# views
gem 'haml-rails'
gem 'mobylette'
gem 'jquery_mobile_rails', '~> 1.3.1'
gem 'backbone-on-rails'
gem 'marionette-rails'
gem 'haml_coffee_assets'
gem 'js-routes'
gem 'simple_form'
gem 'bootstrap-sass'
gem 'font-awesome-rails'
gem 'kaminari'
gem 'bootstrap-kaminari-views'
gem 'redactor-rails'
gem 'wice_grid'
gem 'jcrop-rails'
gem 'fancybox-rails'
gem 'select2-rails', '~> 3.4.8'
gem 'swf_fu'
gem 'flash_cookie_session'
gem 'recaptcha', :require => 'recaptcha/rails'
gem 'google-analytics-rails'

# misc
gem 'activeadmin', '0.6.0'
gem 'wkhtmltopdf-binary'
gem 'wicked_pdf'
gem 'mini_magick'
gem 'redcarpet'
gem 'nokogiri'
gem 'rubyzip'
gem 'standard_deviation'

# dev
gem 'awesome_print'
group :development, :test do
  #gem 'debugger'
  gem 'zeus', '~> 0.13.4.pre2'
  gem "rspec-rails", '~> 2.14.0'
  gem "capybara"
  gem 'poltergeist'
  gem "factory_girl_rails"
  gem "ffaker"
  gem "database_cleaner"
  gem "email_spec"
  #gem 'better_errors'
	gem "meta_request"
	gem 'capistrano'
  gem 'rvm-capistrano'
  gem 'quiet_assets'
  gem 'letter_opener'
  gem 'capybara-screenshot'
  #gem "coffee-script-redux-debugger", :git => "git://github.com/JetBrains/coffee-script-redux-debugger.git"
  gem 'jasmine-rails'
end

group :staging do
  gem 'ruby-prof'
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'turbo-sprockets-rails3'
  gem 'jquery-rails'
  gem 'jquery-ui-rails'
  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyracer' #, :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end
